In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sqlalchemy import create_engine

In [7]:
engine = create_engine("postgresql+psycopg2://postgres:PoPo2021@localhost:5432/mobility_raw")

In [16]:
experiment = pd.read_sql("""SELECT * FROM analytics.mart_experiment_performance""", engine)

In [17]:
experiment.shape

(1748, 24)

In [18]:
experiment.head()

,assignment_id,ticket_id,experiment_name,experiment_group,assigned_at,trip_id,rider_id,city,ride_type,issue_type,...,resolution_minutes,total_handling_minutes,agent_labor_cost,refund_cost,appeasement_cost,total_support_cost,csat_score,csat_satisfied,missing_trip_flag,invalid_resolution_time_flag
0,EXP000001,TK0000032,AV_Guided_Support_v1,Control,2026-06-19 13:44:11,T0000229,R024465,Lakewood,AV,vehicle_access_issue,...,810.0,86.0,30.33,0.00,NaN,30.33,NaN,NaN,0,0
1,EXP000002,TK0000041,AV_Guided_Support_v1,Control,2026-05-03 06:57:52,T0000332,R011953,Metroville,AV,pickup_issue,...,165.0,27.0,10.07,0.00,NaN,10.07,NaN,NaN,0,0
2,EXP000003,TK0000047,AV_Guided_Support_v1,Treatment,2026-06-12 05:11:55,T0000405,R011211,Riverton,AV,trip_status_issue,...,994.0,124.0,46.87,9.00,0.0,55.87,NaN,NaN,0,0
3,EXP000004,TK0000049,AV_Guided_Support_v1,Control,2026-05-17 01:31:05,T0000416,R017117,Metroville,AV,cancellation_issue,...,658.0,73.0,29.36,2.55,0.0,31.91,NaN,NaN,0,0
4,EXP000005,TK0000055,AV_Guided_Support_v1,Control,2026-04-01 20:24:11,T0000466,R007710,Riverton,AV,pickup_issue,...,733.0,60.0,20.05,0.00,NaN,20.05,NaN,NaN,0,0

In [19]:
experiment.info()

<class 'pandas.DataFrame'>
RangeIndex: 1748 entries, 0 to 1747
Data columns (total 24 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   assignment_id                 1748 non-null   str
 1   ticket_id                     1748 non-null   str
 2   experiment_name               1748 non-null   str
 3   experiment_group              1748 non-null   str
 4   assigned_at                   1748 non-null   datetime64[us]
 5   trip_id                       1742 non-null   str
 6   rider_id                      1748 non-null   str
 7   city                          1742 non-null   str
 8   ride_type                     1742 non-null   str
 9   issue_type                    1748 non-null   str
 10  channel                       1748 non-null   str
 11  priority                      1748 non-null   str
 12  was_escalated                 1748 non-null   int64
 13  had_repeat_contact            1748 non-null   int64
 14  resolution_minutes            1747 non-null   float64
 15  total_handling_minutes        1748 non-null   float64
 16  agent_labor_cost              1748 non-null   float64
 17  refund_cost                   1748 non-null   float64
 18  appeasement_cost              650 non-null    float64
 19  total_support_cost            1748 non-null   float64
 20  csat_score                    771 non-null    float64
 21  csat_satisfied                771 non-null    float64
 22  missing_trip_flag             1748 non-null   int64
 23  invalid_resolution_time_flag  1748 non-null   int64
dtypes: datetime64[us](1), float64(8), int64(4), str(11)
memory usage: 501.9 KB

In [20]:
experiment.columns.tolist()

['assignment_id',
 'ticket_id',
 'experiment_name',
 'experiment_group',
 'assigned_at',
 'trip_id',
 'rider_id',
 'city',
 'ride_type',
 'issue_type',
 'channel',
 'priority',
 'was_escalated',
 'had_repeat_contact',
 'resolution_minutes',
 'total_handling_minutes',
 'agent_labor_cost',
 'refund_cost',
 'appeasement_cost',
 'total_support_cost',
 'csat_score',
 'csat_satisfied',
 'missing_trip_flag',
 'invalid_resolution_time_flag']

In [21]:
experiment["experiment_group"].value_counts()

experiment_group
Control      882
Treatment    866
Name: count, dtype: int64

In [22]:
experiment["experiment_group"].value_counts(normalize=True).mul(100).round(2)

experiment_group
Control      50.46
Treatment    49.54
Name: proportion, dtype: float64

In [23]:
experiment.isna().sum()

assignment_id                      0
ticket_id                          0
experiment_name                    0
experiment_group                   0
assigned_at                        0
trip_id                            6
rider_id                           0
city                               6
ride_type                          6
issue_type                         0
channel                            0
priority                           0
was_escalated                      0
had_repeat_contact                 0
resolution_minutes                 1
total_handling_minutes             0
agent_labor_cost                   0
refund_cost                        0
appeasement_cost                1098
total_support_cost                 0
csat_score                       977
csat_satisfied                   977
missing_trip_flag                  0
invalid_resolution_time_flag       0
dtype: int64

In [24]:
experiment_summary = (
    experiment.groupby("experiment_group")
    .agg(
        tickets=("ticket_id", "count"),
        escalation_rate=("was_escalated", "mean"),
        repeat_contact_rate=("had_repeat_contact", "mean"),
        avg_resolution_minutes=("resolution_minutes", "mean"),
        avg_handling_minutes=("total_handling_minutes", "mean"),
        avg_support_cost=("total_support_cost", "mean"),
        avg_csat_score=("csat_score", "mean"),
        csat_rate=("csat_satisfied", "mean")
    )
    .reset_index()
)

In [25]:
experiment_summary

,experiment_group,tickets,escalation_rate,repeat_contact_rate,avg_resolution_minutes,avg_handling_minutes,avg_support_cost,avg_csat_score,csat_rate
0,Control,882,0.315193,0.209751,758.851474,87.391156,39.745658,2.763780,0.230971
1,Treatment,866,0.252887,0.155889,577.314451,77.717090,35.498891,3.169231,0.356410

In [27]:
summary_display = experiment_summary.copy()

rate_columns = ["escalation_rate", "repeat_contact_rate", "csat_rate"]

summary_display[rate_columns] = summary_display[rate_columns].mul(100).round(2)
summary_display[["avg_resolution_minutes", "avg_handling_minutes", "avg_csat_score"]] = summary_display[["avg_resolution_minutes", "avg_handling_minutes", "avg_csat_score"]].round(2)

summary_display

,experiment_group,tickets,escalation_rate,repeat_contact_rate,avg_resolution_minutes,avg_handling_minutes,avg_support_cost,avg_csat_score,csat_rate
0,Control,882,31.52,20.98,758.85,87.39,39.745658,2.76,23.10
1,Treatment,866,25.29,15.59,577.31,77.72,35.498891,3.17,35.64

In [28]:
comparison = experiment_summary.set_index("experiment_group")
comparison

,tickets,escalation_rate,repeat_contact_rate,avg_resolution_minutes,avg_handling_minutes,avg_support_cost,avg_csat_score,csat_rate
experiment_group,,,,,,,,
Control,882,0.315193,0.209751,758.851474,87.391156,39.745658,2.763780,0.230971
Treatment,866,0.252887,0.155889,577.314451,77.717090,35.498891,3.169231,0.356410

In [29]:
treatment_effects = pd.DataFrame({
    "control": comparison.loc["Control"],
    "treatment": comparison.loc["Treatment"]
})
treatment_effects

                           control   treatment
tickets                 882.000000  866.000000
escalation_rate           0.315193    0.252887
repeat_contact_rate       0.209751    0.155889
avg_resolution_minutes  758.851474  577.314451
avg_handling_minutes     87.391156   77.717090
avg_support_cost         39.745658   35.498891
avg_csat_score            2.763780    3.169231
csat_rate                 0.230971    0.356410

In [30]:
treatment_effects["absolute_difference"] = treatment_effects["treatment"] - treatment_effects["control"]

treatment_effects

                           control   treatment  absolute_difference
tickets                 882.000000  866.000000           -16.000000
escalation_rate           0.315193    0.252887            -0.062306
repeat_contact_rate       0.209751    0.155889            -0.053861
avg_resolution_minutes  758.851474  577.314451          -181.537023
avg_handling_minutes     87.391156   77.717090            -9.674066
avg_support_cost         39.745658   35.498891            -4.246766
avg_csat_score            2.763780    3.169231             0.405451
csat_rate                 0.230971    0.356410             0.125439

In [31]:
treatment_effects["relative_change_pct"] = (treatment_effects["treatment"] - treatment_effects["control"]) / treatment_effects["control"] * 100

treatment_effects

,control,treatment,absolute_difference,relative_change_pct
tickets,882.000000,866.000000,-16.000000,-1.814059
escalation_rate,0.315193,0.252887,-0.062306,-19.767558
repeat_contact_rate,0.209751,0.155889,-0.053861,-25.678797
avg_resolution_minutes,758.851474,577.314451,-181.537023,-23.922603
avg_handling_minutes,87.391156,77.717090,-9.674066,-11.069846
avg_support_cost,39.745658,35.498891,-4.246766,-10.684856
avg_csat_score,2.763780,3.169231,0.405451,14.670173
csat_rate,0.230971,0.356410,0.125439,54.309441

In [32]:
treatment_effects.round(3)

,control,treatment,absolute_difference,relative_change_pct
tickets,882.000,866.000,-16.000,-1.814
escalation_rate,0.315,0.253,-0.062,-19.768
repeat_contact_rate,0.210,0.156,-0.054,-25.679
avg_resolution_minutes,758.851,577.314,-181.537,-23.923
avg_handling_minutes,87.391,77.717,-9.674,-11.070
avg_support_cost,39.746,35.499,-4.247,-10.685
avg_csat_score,2.764,3.169,0.405,14.670
csat_rate,0.231,0.356,0.125,54.309